spring:
  application:
    name: job-application-manager

  datasource:
    url: jdbc:h2:mem:jobapplicationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

    jpa:
      hibernate:
        ddl-auto: create-drop
      database-platform: org.hibernate.dialect.H2Dialect
      show-sql: true

    h2:
      console:
        path: /h2-console
        settings:
          web-allow-others: true
  servlet:
    multipart:
      #max-file-count: 5
      max-file-size: 5MB
      max-request-size: 10MB
  file:
    upload-dir: UPLOADS

api:
  endpoint:
    base-url: /api/v1
